USE [master]
GO
CREATE SERVER AUDIT [Audit_Login_User_Change]
TO FILE 
(	FILEPATH = N'C:\Audit\'
	,MAXSIZE = 10 MB
	,MAX_FILES = 5
	,RESERVE_DISK_SPACE = ON
) WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE)
ALTER SERVER AUDIT [Audit_Login_User_Change] WITH (STATE = ON)
GO
CREATE SERVER AUDIT SPECIFICATION [Audit_Spec_Login_User_Change]
FOR SERVER AUDIT [Audit_Login_User_Change]
ADD (SERVER_PRINCIPAL_CHANGE_GROUP),
ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP),
ADD (SERVER_PERMISSION_CHANGE_GROUP),
ADD (LOGIN_CHANGE_PASSWORD_GROUP),
ADD (DATABASE_PRINCIPAL_CHANGE_GROUP),
ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
ADD (DATABASE_PERMISSION_CHANGE_GROUP),
ADD (USER_CHANGE_PASSWORD_GROUP)
WITH (STATE = ON)
GO
