SELECT ss.name AS [Schema_Name], so.name AS [Object_Name], so.type_desc, 
	CASE WHEN sm.[definition] LIKE '%FORCE ORDER%' 
			OR sm.[definition] LIKE '%KEEP PLAN%' 
			OR sm.[definition] LIKE '%KEEPFIXED PLAN%' 
			OR sm.[definition] LIKE '%MAXDOP%' 
			OR sm.[definition] LIKE '%OPTIMIZE FOR%' 
			OR sm.[definition] LIKE '%QUERYTRACEON%' 
			OR sm.[definition] LIKE '%USE HINT%' 
			OR sm.[definition] LIKE '%TABLE HINT%' 
			OR sm.[definition] LIKE '%RECOMPILE%' 
					THEN '[QUERY Hint]'
	WHEN sm.[definition] LIKE '%INDEX%' 
	OR sm.[definition] LIKE '%FORCESEEK%' 
	OR sm.[definition] LIKE '%FORCESCAN%' 
	OR sm.[definition] LIKE '%HOLDLOCK%' 
	OR sm.[definition] LIKE '%NOLOCK%' 
	OR sm.[definition] LIKE '%PAGLOCK%' 
	OR sm.[definition] LIKE '%READUNCOMMITTED%' 
	OR sm.[definition] LIKE '%REPEATABLEREAD%' 
	OR sm.[definition] LIKE '%ROWLOCK%' 
	OR sm.[definition] LIKE '%SERIALIZABLE%' 
	OR sm.[definition] LIKE '%TABLOCK%' 
	OR sm.[definition] LIKE '%TABLOCKX%' 
	OR sm.[definition] LIKE '%UPDLOCK%' 
	OR sm.[definition] LIKE '%XLOCK%' 
	THEN '[TABLE Hint]'
	WHEN sm.[definition] LIKE '%MERGE JOIN%'
		OR sm.[definition] LIKE '%LOOP JOIN%'
		OR sm.[definition] LIKE '%HASH JOIN%' THEN '[JOIN Hint]' END AS Hint
FROM sys.sql_modules sm
INNER JOIN sys.objects so ON sm.[object_id] = so.[object_id]
INNER JOIN sys.schemas ss ON so.[schema_id] = ss.[schema_id]
WHERE (sm.[definition] LIKE '%FORCE ORDER%' 
			OR sm.[definition] LIKE '%KEEP PLAN%' 
			OR sm.[definition] LIKE '%KEEPFIXED PLAN%' 
			OR sm.[definition] LIKE '%MAXDOP%' 
			OR sm.[definition] LIKE '%OPTIMIZE FOR%' 
			OR sm.[definition] LIKE '%QUERYTRACEON%' 
			OR sm.[definition] LIKE '%USE HINT%' 
			OR sm.[definition] LIKE '%TABLE HINT%' 
			OR sm.[definition] LIKE '%RECOMPILE%' 
	OR sm.[definition] LIKE '%INDEX%' 
	OR sm.[definition] LIKE '%FORCESEEK%' 
	OR sm.[definition] LIKE '%FORCESCAN%' 
	OR sm.[definition] LIKE '%HOLDLOCK%' 
	OR sm.[definition] LIKE '%NOLOCK%' 
	OR sm.[definition] LIKE '%PAGLOCK%' 
	OR sm.[definition] LIKE '%READUNCOMMITTED%' 
	OR sm.[definition] LIKE '%REPEATABLEREAD%' 
	OR sm.[definition] LIKE '%ROWLOCK%' 
	OR sm.[definition] LIKE '%SERIALIZABLE%' 
	OR sm.[definition] LIKE '%TABLOCK%' 
	OR sm.[definition] LIKE '%TABLOCKX%' 
	OR sm.[definition] LIKE '%UPDLOCK%' 
	OR sm.[definition] LIKE '%XLOCK%' 
	OR sm.[definition] LIKE '%MERGE JOIN%'
	OR sm.[definition] LIKE '%LOOP JOIN%'
	OR sm.[definition] LIKE '%HASH JOIN%') 
AND OBJECTPROPERTY(sm.[object_id],'IsMSShipped') = 0;