#This Sample Code is provided for the purpose of illustration only and is not intended to be used in a production environment.
#THIS SAMPLE CODE AND ANY RELATED INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED,
#INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
#We grant you a nonexclusive, royalty-free right to use and modify the Sample Code and to reproduce and distribute
#the object code form of the Sample Code, provided that you agree:
#(i) to not use Our name, logo, or trademarks to market Your software product in which the Sample Code is embedded;
#(ii) to include a valid copyright notice on Your software product in which the Sample Code is embedded; and
#(iii) to indemnify, hold harmless, and defend Us and our suppliers from and against any claims or lawsuits, including attorneys' fees, that arise or result from the use or distribution of the Sample Code. 
#
# Module manifest for module 'SQLRES'
#
# Generated by: Oliver Hahn
#
# Generated on:   04/16/2013
# Last edited on: 06/12/2019
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = ''

# Version number of this module.
ModuleVersion = '5.0.1.3'

# ID used to uniquely identify this module
GUID = '440abcb2-4698-4b33-9e6c-982cd5734d70'

# Author of this module
Author = 'Oliver Hahn'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '2019'

# Description of the functionality provided by this module
Description = 'SQLRES PowerShell Module'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = '3.0'

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @()
#'.\Modules\Load Scoping.ps1';
#)

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules = @(
'.\Modules\Scope Environment.psm1';
'.\Modules\Confirm-Azure.psm1';
'.\Modules\Show-EULA.psm1';
'.\Modules\Show-ConnectToSQLServer.psm1';
'.\Modules\Show-SaveWindowsCredentials.psm1';
'.\Modules\Remove Scoping.psm1';
'.\Modules\ReScope Environment.psm1';
'.\Modules\Start DebugLog.psm1';
'.\Modules\Stop DebugLog.psm1';
'.\Modules\Clone Database.psm1';
'.\Modules\Remove Database.psm1';
'.\Modules\Create Database Backup.psm1';
'.\Modules\Restore Database Backup.psm1';
'.\Modules\Master corruption.psm1';
'.\Modules\Model corruption.psm1';
'.\Modules\MSDB corruption.psm1';
'.\Modules\Boot Page corruption.psm1';
'.\Modules\Block TCP port.psm1';
'.\Modules\Disable Public NIC.psm1';
'.\Modules\DCM Page corruption.psm1';
'.\Modules\SGAM Page corruption.psm1';
'.\Modules\GAM Page corruption.psm1';
'.\Modules\IAM Page corruption.psm1';
'.\Modules\IAM User Page corruption.psm1';
'.\Modules\PFS Page corruption.psm1';
'.\Modules\Data Page corruption.psm1';
'.\Modules\Data Purity corruption.psm1';
'.\Modules\Fulltext index corruption.psm1';
'.\Modules\File Header Corruption.psm1';
'.\Modules\Index Page corruption.psm1';
'.\Modules\Crash SystemResource.psm1';
'.\Modules\DenyLogonAsAService.psm1';
'.\Modules\DenyLogonAsAService - Repair.psm1';
'.\Modules\Deadlocked Schedulers.psm1';
'.\Modules\Suspect Database.psm1';
'.\Modules\Compressed Database.psm1';
'.\Modules\SystemTable corruption 1.psm1';
'.\Modules\SystemTable corruption 2.psm1';
'.\Modules\SystemTable corruption 3.psm1';
'.\Modules\ERRORLOG NoRights.psm1';
'.\Modules\SQLAGENT.OUT NoRights.psm1';
'.\Modules\TempDB NoRights.psm1';
'.\Modules\TempDB Issue.psm1';
'.\Modules\cliconfg wrong alias.psm1';
'.\Modules\cliconfg wrong alias - Repair.psm1';
'.\Modules\delete SystemResource.psm1';
'.\Modules\Who dropped the table.psm1';
'.\Modules\Lockout from Sysadmin.psm1';
'.\Modules\Logon Trigger Issue.psm1';
'.\Modules\Delete Cluster Computer Account (CNO).psm1';
'.\Modules\Delete IPAddress Cluster Resource.psm1';
'.\Modules\Delete NetworkName Cluster Resource.psm1';
'.\Modules\Delete SQLServer Cluster DLL.psm1';
'.\Modules\Delete SQLAgent Cluster DLL.psm1';
'.\Modules\Delete SQLServer Cluster Resource.psm1';
'.\Modules\Delete SQLAgent Cluster Resource.psm1';
'.\Modules\Delete TDE Certificate.psm1';
'.\Modules\Remove SQLServer Disk Dependencies.psm1';
'.\Modules\Cluster Quorum Loss.psm1';
'.\Modules\MSDTC cluster resource failure.psm1';
'.\Modules\Select TestCase.psm1';
'.\Modules\Load Scoping.psm1';
'.\Modules\Create Admin Shortcut.psm1';
'.\Modules\Block HADR endpoint port.psm1';
'.\Modules\Delete HADR cluster DLL.psm1';
'.\Modules\Delete HADR cluster Resource.psm1';
'.\Modules\Revoke CONNECT on HADR endpoint.psm1';
'.\Modules\TailLog Backup of model DB.psm1';
'.\Modules\Change Default Instance TCP Port.psm1';
'.\Modules\Disable SQL Browser Service.psm1';
'.\Modules\Max Server Memory too low.psm1';
'.\Modules\Generate BSOD.psm1';
'.\Modules\Stop HADR endpoint.psm1';
'.\Modules\Witness Lost - Secondary Lost - Primary Left Exposed.psm1';
'.\Modules\Witness Lost - Primary Lost - Secondary Left Exposed.psm1';
'.\Modules\Offline Data Disk.psm1';
'.\Modules\Offline TLog Disk.psm1';
'.\Modules\Fail HADR Listener.psm1';
'.\Modules\Hide Instance.psm1';
'.\Modules\Disable Network Protocols.psm1';
'.\Modules\Wrong TLS Certificate Thumbprint.psm1';
'.\Modules\Split Availability Set.psm1';
'.\Modules\Block Cluster Communication.psm1';
'.\Modules\Move SQL Server to Available Storage.psm1';
'.\Modules\NoRights on Quorum.psm1';
'.\Modules\SQLAgent NoRights on RegHive.psm1';
'.\Modules\Delete SYSTEM login.psm1';
'.\Modules\Eating Memory.psm1';
'.\Modules\Tools.psm1';
'.\Modules\Repair Previous TestCase.psm1';
)

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''

}

